### PR TITLE
Remove gain correction for old SI

### PR DESCRIPTION
**Pull request by alejoe91**
Fix https://github.com/catalystneuro/nwb-conversion-tools/issues/369

## Motivation

Remove unused code and code to retrieve correct gains and offsets for old extractors as now it's done in the `OldToNewRecording` (https://github.com/SpikeInterface/spikeinterface/pull/462)

## How to test the behavior?
```
import spikeextractors as se
from nwb_conversion_tools import write_recording

rec, sort = se.example_datasets.toy_example()
rec.set_channel_gains(0.1)
rec_sub = se.SubRecordingExtractor(end_frame=100)

write_recording(rec_sub, save_path="test_gains.nwb")
# the gain is correctly set to 0.1 in the nwb file
```

## Checklist

- [x] Have you checked our [Contributing](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/docs/contribute.rst) document?
- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/nwb-conversion-tools/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XXX` where `XXX` is the issue number?

### CODE REVIEW

**Comment by alejoe91** [comment]
SI PR merged to master: https://github.com/SpikeInterface/spikeinterface/pull/462

**Comment by alejoe91** [comment]
Also required a small bug fix in spikeextractors: https://github.com/SpikeInterface/spikeextractors/pull/670

**Comment by CodyCBakerPhD** [comment]
@alejoe91 In case you missed by chance; some of these changes to spikeextractors broke downstream Intan stuff. I had to pin spikeextractors to a previous hash to keep `main` stable for now: https://github.com/catalystneuro/nwb-conversion-tools/pull/373, but if you can fix that upstream or otherwise isolate the problem for discussion, I'd be appreciated prior to next release

**Comment by alejoe91** [comment]
Sure I'll check

**Comment by alejoe91** [comment]
@CodyCBakerPhD fixed here: https://github.com/SpikeInterface/spikeinterface/pull/468
(stupid bug from my side). Tests should pass now

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Thanks for the fast response; I bumped the versions, waiting to see what the CI thinks

**Comment by alejoe91** [comment]
Passing!!!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
