### PR TITLE
propagate buffer_mb argument from spikeextractors

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@alejoe91 @luiztauffer Depends on https://github.com/SpikeInterface/spikeextractors/pull/578

The `buffer_mb` argument has been available at the `add_electrical_series` level for quite a while, but was never able to be specified at the highest level of `write_recording`.

Now that we are running multiple large-scale raw data conversions in parallel, a facet unlikely to soon change, this argument will give us a much greater degree of control over the processing resource specification.

### CODE REVIEW

**Comment by bendichter** [comment]
I like it

**Review by bendichter — APPROVED** [review]

**Comment by bendichter** [comment]
I like this but maybe we should wait for spikeexractors to release this feature?

**Comment by CodyCBakerPhD** [comment]
@bendichter It's been merged to master on se - it should therefore be included in the big release of the return_scaled feature once we have that ironed out

**Comment by alejoe91** [comment]
Looks good to me @CodyCBakerPhD !!

**Pull request merged**
