### PR TITLE
Small refactor of `test_gin_behavior` to pin new CI error

### PR DESCRIPTION
**Pull request by h-mayorquin**
The goal of this PR is to pin down the error that we are getting in #531.

I did a small refactor in the test that is failing to see if the error still appears / is reproducible here.

### CODE REVIEW

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
If you notice,  the CI is downloaded the ecephys data again instead of using the cache here. Shouldn't it be using the cache from the other tests that we just ran in the other PR?

**Comment by CodyCBakerPhD** [comment]
> Shouldn't it be using the cache from the other tests that we just ran in the other PR?

Not until GitHub Caching Action allows either a control functionality, or better handling of a 'global' cache 😉 One of my only complaints about the functionality. See https://github.com/actions/cache/issues/692 and https://github.com/actions/cache/issues/342

**Comment by h-mayorquin** [comment]
> > Shouldn't it be using the cache from the other tests that we just ran in the other PR?
> 
> Not until GitHub Caching Action allows either a control functionality, or better handling of a 'global' cache wink One of my only complaints about it. See [actions/cache#692](https://github.com/actions/cache/issues/692) and [actions/cache#342](https://github.com/actions/cache/issues/342) for background.

Interesting. So, the scope of the cache is within this branch and the parent one (which has not been run and therefore cache miss?).

**Comment by CodyCBakerPhD** [comment]
> Interesting. So, the scope of the cache is within this branch and the parent one (which has not been run and therefore cache miss?).

Theoretically, but it also occasionally fails to find any parent. Also, none of this is specifiable and is at the mercy of the CI instance.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Great, thanks for looking into that!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
