### PR TITLE
Limit creation of initial nwbfile object

### PR DESCRIPTION
**Pull request by luiztauffer**
fix for append to existing file

### CODE REVIEW

**Comment by luiztauffer** [comment]
@CodyCBakerPhD this should solve for the last PR problem

**Comment by luiztauffer** [comment]
fix #140

**Comment by CodyCBakerPhD** [comment]
That does fix it, but it seems hacky isn't very thin - what use case does this come up in and is there no way around it in the downstream stuff?

**Comment by CodyCBakerPhD** [comment]
@luiztauffer What problem does this create in your conversion? All the possibilities I can image can be resolved by setting overwrite appropriately - is that the case or am I missing something?

**Comment by luiztauffer** [comment]
this piece of code should not be executed if we're just adding data to an existing nwb file:
https://github.com/catalystneuro/nwb-conversion-tools/blob/c7a2989243d9077e4db0c4f4468fbff92fee9daf/nwb_conversion_tools/nwbconverter.py#L136-L151

**Comment by CodyCBakerPhD** [comment]
This piece of code will overwrite the nwbfile object in that case, so I don't see how this could 'cause a problem' in any of our conversions:

https://github.com/catalystneuro/nwb-conversion-tools/blob/update_version/nwb_conversion_tools/nwbconverter.py#L158-L165

**Comment by luiztauffer** [comment]
@CodyCBakerPhD  you're right, in principle it wouldn't. Nevertheless, we should not run that piece of code, even if that will be overwritten, a matter of good practice imo.
I see now that we could indeed use `or overwrite` in that first if statement (instead of `nwbfile_path is not None and not Path(nwbfile_path).is_file()`), maybe that would actually be better

**Comment by CodyCBakerPhD** [comment]
Yeah, we were aware of that fact when we wrote this code, but it's such a small inefficiency it doesn't really matter (one dictionary, one completely minimal NWB object). While it's a matter of practice certainly, it's also (I would argue) a better matter of practice to not expand a single logical `if` check out to four logical places (for doing what we want here, you'd need `nwbfile_path is not None and not Path(nwbfile_path).is_file() and not overwrite`).

A better way would be to make a `conversion_tool` function for generating a default NWBFile, and call it appropriately inside the `save_to_file` blocks.

Point being, this patch is listed as a 'fix' for a current conversion, not a performance enhancement, and is delaying our latest release. Since it changes nothing in terms of functionality I'll go ahead with the new release while you work on improving the code checks for this.

**Comment by luiztauffer** [comment]
@CodyCBakerPhD 

When appending data to an existing file we should not require metadata, and this for example will break the code. Example:

```
converter.run_conversion(
    metadata={},
    nwbfile_path=path_to_output_nwb, 
    overwrite=False,
    conversion_options=conversion_options
)
```

Again, we are running a piece of code unnecessary in this case. Please accept the proposed fix or make a fix more of your taste here and let’s release it. The current nwb-conversion-tools release does not work for Movshon

**Comment by CodyCBakerPhD** [comment]
@luiztauffer Thanks for providing the source of  your issues.

Ultimately, that's a failure of our (a) logical checks on the passed metadata structure prior to use and (b) non-safe dictionary retrieval. While your previous suggested changes would have forced your Movshon conversion through, they wouldn't have resolved that core issue so it would have come up again at a later point in time. And also would have broken other conversions without the proper `overwrite` interaction.

But of course I am always happy to implement these changes myself! Working on it now.

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD
> 
> When appending data to an existing file we should not require metadata

We should _always_ require metadata, and encourage that it be retrieved from the call to `my_converter.get_metadata()`. You never know what contained interfaces in that converter might contain information that isn't already in the NWBFile you're intending to append. In fact, two of our recent conversions (Tank, Mease) support this as an intended usage. I'm pretty sure that if you call `get_metadata()` in your conversion, instead of passing an empty dictionary, this error should not occur since `get_metadata()` from the super `NWBConverter` class will never return an empty dictionary - an importantly, will contain the keys at the source of this issue.

Anyway, [I've raised this as an issue with v0.7.0](https://github.com/catalystneuro/nwb-conversion-tools/issues/147) so we can refer back it it, and [made a separate PR that fixes that](https://github.com/catalystneuro/nwb-conversion-tools/pull/148). If it fixes your issue, then I'll close this PR.

Also, remember that we encourage (as a code style) the use of dictionary literals whenever possible. I.e., `metadata=dict()`.

**Pull request closed without merging**
