### PR TITLE
reorganize datainterfaces directory

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
[fix Issue #153](https://github.com/catalystneuro/nwb-conversion-tools/issues/153) 

## Motivation

The original method of appending newly made data interfaces under a nesting structure of simple `nwb-conversion-tools/datainterfaces/*` was becoming inflated, making it difficult to navigate. The new structure nests them by modality in the list `["ecephys", "ophys", "behavior"]`. In the future, planning to extend to `"icephys"` as well.

## How to test the behavior?

The testing infrastructure has either been altered along the new import structure, or is robust to those changes.

## Checklist

- [X] Have you checked our [Contributing](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/docs/contribute.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style? Read about [PEP8](https://www.python.org/dev/peps/pep-0008/) and [black](https://black.readthedocs.io/en/stable/the_black_code_style.html).
- [X] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/nwb-conversion-tools/pulls) for the same change?
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number?

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
The one interesting special case is our most recent interface, Axona, which has a PositionInterface (`behavior` type) attached to the RawIO and thus is still contained in the same file as the `ecephys` RecordingExtractor.

Tests are currently failing because the CI is checking out the main branch rather than the new one - see this discussion which had some tips I've tried but so far no luck: [https://github.com/actions/checkout/issues/15](https://github.com/actions/checkout/issues/15)

**Comment by CodyCBakerPhD** [comment]
a) Of course, there are plenty of other formats that might mirror that. For instance, the `mease-lab-to-nwb` project had some `intan` data that had accelerometer channels plugged in and thus contained in the 'raw' data format. If we hypothetically made a general  IntanAccelerometer interface, should that interface then belong within the `ecephys/intan` nesting or should both this and the Axona be separated under the `behavior/<format name>` (even though that format might also exist in `ecephys`)?

b) It's hard to imagine what movie files wouldn't reflect behavior in some way, but perhaps the MovieDataInterface should belong under a `misc` nesting header?

@bendichter @luiztauffer @sbuergers Any thoughts?

**Comment by bendichter** [comment]
I see the issue, but I say if it's primarily ecephys let's put it in ecephys, even if it can contains behavioral data as well.

**Comment by luiztauffer** [comment]
I also prefer this proposed organization, here are some points:

1. Shouldn’t we wait for #181 and #183 to be merged into master? Otherwise we might have bad conflicts to solve.

2. We should move the modality-specific base interfaces to their modality-specific folders. Examples: `basesegmentationextractorinterface.py` to `datainterfaces/ophys` and `baserecordingextractorinterface` to `datainterfaces/ecephys`. I think `basedatainterface.py` and `nwbconverter.py` can keep living where they are.

With this re-organization of the package I would include some other changes and clean up:

3. The file named `auto_qc.py` doesn’t seem to be used, let’s consider removing it. If there’s any use for the functions in it, we can port them to some utils-like file.

4. We should consider renaming the file named `conversion_tools.py` (maybe `misc.py`) and relocating to it `/utils`.

5. Folder `/schemas` to be renamed `/schema_examples` and the file `metafile.schema.json` to be renamed `metadata_schema.json` and moved there. Probably also this file content needs review, but that’s for later.

6. `/datainterfaces/interface_utils` renamed to `/datainterfaces/utils`

These changes will also requires fixing imports here and there. I could do these changes once we tackle the first point.

**Comment by CodyCBakerPhD** [comment]
@luiztauffer Thanks for taking the time to write all that out, it helps a lot.

1. I'm not too concerned about that, would rather get this through sooner rather than later. And #181 still has a ways to go yet.
2. Agreed, I've made that change now.
3. Git Blame shows the file `auto_qc.py` is almost entirely from @bendichter from 2 years ago - since I have no idea what it's used for, I'll defer to him on what to do with it. I will point out one function there `check_constant_rate` has a slightly different version but the same functionality present in the `conversion_tools.py`.
4. Definitely agree on moving to `utils`, which is now changed. The naming convention is inherited from `spikeextractors`, etc. where it contains all general-purpose util like functions that one might find handy during conversions.
5. Can you make the schema naming changes since you're more familiar with them?
6. Actually, on this one, I wonder if we can go a step better. All the files in this folder pertain specifically to certain interfaces and are in no way general util-like functions. We could instead dismantle the `interface_utils` header and put those individual files under the same nesting as their respective interfaces. A question that remains here is between (i), `interface_utils/brpylib.py` -> `datainterfaces/ecephys/blackrock/brpylib.py`, leaving some of the interfaces under `/datainterfaces/ecephys/` in lone files and others that need supplementary functions in folders paired with those helper functions, or (ii) `interface_utils/brpylib.py` -> `datainterfaces/ecephys/brpylib.py` alongside all the other `ecephys` related files. Either way, this prevents these types of hyperspecific utils from becoming disjointed in the location across the repo. @luiztauffer which would you prefer?

**Comment by luiztauffer** [comment]
Yes, I’m fine with following the SpikeInterface structure and having one extra folder per DataInterface, we can then store DataInterface-specific auxiliary files directly there. This organizes it better when the number of DataInterfaces grow too much, also helps separating them from the base shared modules. So I’d vote for `datainterfaces/ecephys/blackrock/brpylib.py` style

**Comment by CodyCBakerPhD** [comment]
@luiztauffer Check out the latest commit distributing the ophys interfaces in an identical manner - how does it look to you?

**Review by luiztauffer — APPROVED** [review]
looks good to me

**Comment by luiztauffer** [comment]
@CodyCBakerPhD you wan to wait for #181 or should we merge it now?

**Comment by CodyCBakerPhD** [comment]
@luiztauffer It hopefully shouldn't cause any conflicts if merges go properly onto master and then from master onto the dev branches, so let's go ahead with it now

**Comment by Saksham20** [comment]
lets merge this?

**Pull request merged**
