### PR TITLE
source data schema and example

### PR DESCRIPTION
**Pull request by luiztauffer**
v 0.1.0

### CODE REVIEW

**Comment by luiztauffer** [comment]
Here are tentative examples of source input data and schema. Those will be generated by the specific converters in the backend and returned to the GUI for creating the Forms in the first step: https://github.com/catalystneuro/nwb-conversion-tools/issues/54#issuecomment-663249122

@CodyCBakerPhD @bendichter can you check it out and let me know if these are covering all uses cases (files, directories and boolean options)? Or any other fields / types you foresee we might need?

**Comment by bendichter** [comment]
@luiztauffer what do you think of this schema? (I accidentally merged, meant to create a PR)

**Comment by bendichter** [comment]
I'm tempted to get rid of the source_files vs. conversion_options and just put them all in the same object. @luiztauffer, what would you think about that?

**Comment by luiztauffer** [comment]
I included two modifications now on input data and schema handling:
1. when the input_data comes to the converter, it needs to know where to route each key:value pair
For example, this data will be received by a converter and should have specific parts correctly sent to an Ophys and an Ecephys data interfaces:
```json
{
	"source_data": {
		"path_calibration": "path_to/calibration.h5",
		"path_raw": "path_to/raw.h5",
		"path_tiff": "path_to/image.tif",
		"path_processed": "path_to/processed_data.h5"
	},
	"conversion_options": {
		"ophys_raw": true,
		"ophys_processed": true,
		"ecephys_spiking": true,
		"ecephys_processed": true
	}
}
```
this routing is important because of this:
https://github.com/catalystneuro/nwb-conversion-tools/blob/2a29c85ebd449a13356c167697387cf780324a60/nwb_conversion_tools/nwbconverter.py#L24-L25

**Comment by luiztauffer** [comment]
2. when updating `input_schema['properties']` in series with several DataInterfaces, it needs to be a deep update. This must be working well now with these changes

**Comment by bendichter** [comment]
@luiztauffer OK, can you fix merge conflicts?

**Comment by luiztauffer** [comment]
> @luiztauffer OK, can you fix merge conflicts?

done

**Comment by luiztauffer** [comment]
I believe this fixes #61 
@bendichter @CodyCBakerPhD ?

**Pull request merged**
