### PR TITLE
added intan recording interface

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@bendichter I'll add the get_metadata() funciton for this later today, just getting this up for now

### CODE REVIEW

**Comment by bendichter** [comment]
> @bendichter I'll add the get_metadata() funciton for this later today, just getting this up for now

Cool. You can use the Draft PR for work in progress PRs

**Comment by CodyCBakerPhD** [comment]
@bendichter Right you are; changed that. I'll try to be better about listing PR's as drafts while they are still in progress!

**Comment by CodyCBakerPhD** [comment]
@bendichter OK, added and debugged the `get_metadata()` part as it relates at least to the Syntalos project.

**Comment by bendichter** [comment]
@CodyCBakerPhD Looks good. Does this PR address the int16 vs float32 issue?

**Comment by CodyCBakerPhD** [comment]
@bendichter No, waiting on @alejoe91 to make those core changes to either pyintan or the intanRecordingExtractor get_traces(). I think most of that issue can be resolved entirely outside of nwb-conversion-tools

**Pull request merged**
