### PR TITLE
Add black auto-formatting

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
## Motivation

For the sake of better enforcement of code formatting, this runs a check on every PR for corrections to be made according to the `black` [style](https://black.readthedocs.io/en/stable/).

Based off this example: [https://github.com/pre-commit/action](https://github.com/pre-commit/action)

## How to test the behavior?

Should show up as an extra PR condition. (Shouldn't be required for merge, however).

## Checklist

- [X] Have you checked our [Contributing](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/docs/contribute.rst) document?
- [X] Have you ensured the PR description clearly describes the problem and solutions?
- [X] Is your contribution compliant with our coding style? Read about [PEP8](https://www.python.org/dev/peps/pep-0008/) and [black](https://black.readthedocs.io/en/stable/the_black_code_style.html). - Of course, this may not have to be asked anymore.
- [X] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/nwb-conversion-tools/pulls) for the same change?

### CODE REVIEW

**Comment by bendichter** [comment]
@CodyCBakerPhD does this automatically perform black formatting or does it warn when code does not follow black? Why is black listed in requirements.txt? That seems unnecessary. Honestly, it doesn't seem necessary in requirements-dev.txt either.

**Comment by CodyCBakerPhD** [comment]
@bendichter I'm experimenting with a few things, this is mostly to see what the CI does.

See [https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) for another example I'm trying

**Comment by CodyCBakerPhD** [comment]
@bendichter OK, I think I landed on the process I like the most. Credit to this nice blog on the topic: [https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/](https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/)

The changelog is a bit much to go through looking for what actually changed aside from the enforcement of black across the entire repo, so here are the condensed changes required to make it happen

1. New workflow, no changes to requirements or anything. [https://github.com/catalystneuro/nwb-conversion-tools/blob/1ef6decda9e3773faca844a1e8c1c374b20a18b2/.github/workflows/auto-format.yml](https://github.com/catalystneuro/nwb-conversion-tools/blob/1ef6decda9e3773faca844a1e8c1c374b20a18b2/.github/workflows/auto-format.yml)

The workflow operates by running black on the entire directory (previous attempts at the CI also did this, but only reformatted the code inside the CI environment), then pushes those changes back to the originating PR automatically (the user will have to git fetch/pull to update their local branch to the correctly formatted changes if they didn't run black locally beforehand).

2. Parameters of the black formatting (line length, file exclusion, etc. [https://github.com/catalystneuro/nwb-conversion-tools/blob/1ef6decda9e3773faca844a1e8c1c374b20a18b2/pyproject.toml](https://github.com/catalystneuro/nwb-conversion-tools/blob/1ef6decda9e3773faca844a1e8c1c374b20a18b2/pyproject.toml)

**Review by bendichter — APPROVED** [review]
Looks good, let's see how it works for us

**Comment by CodyCBakerPhD** [comment]
OK here goes. In principle shouldn't create much conflict with current PRs/branches, but at least everything branched from main after today will be much cleaner.

**Pull request merged**
