### PR TITLE
added api for tools in documentation

### PR DESCRIPTION
**Pull request by h-mayorquin**
## Motivation

Added an API display functionality for the `nwb_conversion_tools.tools` in the documentation.

## Checklist

- [x] Have you checked our [Contributing](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/docs/contribute.rst) document?
- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/nwb-conversion-tools/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XXX` where `XXX` is the issue number?

### CODE REVIEW

**Comment by bendichter** [comment]
@CodyCBakerPhD , can we get this to build automatically?

**Comment by CodyCBakerPhD** [comment]
@bendichter Webhook should be working now

**Comment by bendichter** [comment]
@CodyCBakerPhD awesome, how did you do that?

**Comment by bendichter** [comment]
can we reformat the docstrings so these look better?

image

**Comment by bendichter** [comment]
otherwise, lgtm!

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD awesome, how did you do that?

It just had to be re-synced on the 'Integrations' tab of the ReadtheDocs admin page


> can we reformat the docstrings so these look better?

For docstrings we need to think about how it looks when displayed both via the `some_function?` command as well as how the API autodoc renders it.

What we could do is try to setup the `conf.py` to convert certain parts of function docstrings read via `automodule` to parse with `.. code-block:: python` instead of as text.

That might take some tinkering; in the meantime, we could hard code it directly into the docstrings (which render as `rst`) but that would then make the in-console display look less nice.

**Comment by bendichter** [comment]
@CodyCBakerPhD how about this?

image

with code:

https://github.com/catalystneuro/nwb-conversion-tools/blob/7ed60c26a4db33c240555d82f7ca8193b139e82d/nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py#L94-L103

**Comment by CodyCBakerPhD** [comment]
@bendichter Yeah, that looks good for both approaches!

BTW do you know how to fix the black-style formatting in the readthedocs? From #422 I thought it was supposed to apply to the blue box (function definition), but it seems to be working on the 'parameters' (docstring) level at the moment. I think you mentioned it might need a specific `sphinx` version? If so maybe we can try pinning that version in the `requirements-rtd.txt`, which is the last thing to install on a readthedocs build

**Comment by CodyCBakerPhD** [comment]
Apparently the webhook doesn't re-build when you update the branch from master.

Heres the unhidden wep link: https://nwb-conversion-tools.readthedocs.io/en/documentation_add_api_for_tools/api/tools.spikeinterface.html

Changes specific to this PR LGTM

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by bendichter** [comment]
let me update the rest of the metadata sections first

**Pull request merged**
