### PR TITLE
add conversion guide

### PR DESCRIPTION
**Pull request by bendichter**
@CodyCBakerPhD and/or @Saksham20  can you help me complete this and get it into the readthedocs?

### CODE REVIEW

**Comment by bendichter** [comment]
https://gist.github.com/bendichter/6402da4138728cc59ab95b87021cab35#file-nwb_conversion-md

**Comment by CodyCBakerPhD** [comment]
@bendichter Yep, I'll work on this later today and early tomorrow, try to get it done before our meeting.

**Comment by CodyCBakerPhD** [comment]
@bendichter It's been on readthedocs for a while, granted the version without nice buttons. I'll keep working on how to do that in .rst but for the purposes of a new nwb-conversion-tools release this should be good enough.

Also, added the fancier looking markdown to the local repo documentation so people can find it in both places.

**Comment by bendichter** [comment]
@CodyCBakerPhD it looks like readthedocs supports markdown. Can you look into that?

**Comment by bendichter** [comment]
https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx

**Comment by bendichter** [comment]
https://myst-parser.readthedocs.io/en/latest/using/intro.html

**Comment by CodyCBakerPhD** [comment]
@bendichter OK, this is all setup now! [https://nwb-conversion-tools.readthedocs.io/en/conversion_guide/index.html](https://nwb-conversion-tools.readthedocs.io/en/conversion_guide/index.html)

I had an issue on my end with the pages not updating the right theme, but after trying different devices/browsers I think it may have just been a local caching thing in Chrome

**Pull request merged**
