### PR TITLE
return nwbfile

### PR DESCRIPTION
**Pull request by bendichter**
returning the nwbfile object in write_recording and write_sorting allows us to build the nwbfile in memory

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@bendichter We currently operate on the `nwbfile` in memory as a pointer (https://github.com/catalystneuro/nwb-conversion-tools/blob/main/nwb_conversion_tools/nwbconverter.py#L171-L172): this is how the `NWBConverter` class collects data across multiple interfaces prior to a single write operation. If you really do want a return structure for some other reason, we should mirror the optional argument behavior with the original behavior as default to avoid breaking back-compatibility (https://github.com/catalystneuro/nwb-conversion-tools/blob/main/nwb_conversion_tools/nwbconverter.py#L116 -> https://github.com/catalystneuro/nwb-conversion-tools/blob/main/nwb_conversion_tools/nwbconverter.py#L155 -> https://github.com/catalystneuro/nwb-conversion-tools/blob/main/nwb_conversion_tools/nwbconverter.py#L181)

**Comment by bendichter** [comment]
I don't understand, what's wrong with returning `nwbfile`?

**Comment by CodyCBakerPhD** [comment]
I see; you are relying on the first call to a  `write_*` method to instantiate your `nwbfile` object, so something like

```python
metadata = dict(NWBFile=dict(session_start_time=datetime(...), ...), ...)  # required to specify the correct start time
nwbfile = write_recording(recording=my_ap_recording, metadata=metadata)
write_recording(recording=my_lfp_recording, nwbfile=nwbfile, metadata=metadata)
```

in which case this change should be fine. It shouldn't break the current in-place usage since the returned output value would simply not be assigned to a value in the functions namespace.

**Review by CodyCBakerPhD — DISMISSED** [review]

**Comment by CodyCBakerPhD** [comment]
Actually it occurs to be looking over those functions that a couple things will need to be changed for this to work as expected; I'll open them in a separate PR pointing to this and test it out

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
