### PR TITLE
Make imaging extrator interface an abstract class

### LINKED ISSUE #557: this class should be abstract
https://github.com/catalystneuro/nwb-conversion-tools/blob/07e958d7564eb12d00a5ff5fabe661677d023efa/src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py#L19

### PR DESCRIPTION
**Pull request by h-mayorquin**
Should fix #557

### CODE REVIEW

**Review by bendichter — APPROVED** [review]
looks good. Feel free to merge when tests pass

**Comment by h-mayorquin** [comment]
It seems that the errors are the ones in #560.

**Comment by CodyCBakerPhD** [comment]
> It seems that the errors are the ones in https://github.com/catalystneuro/nwb-conversion-tools/pull/560.

Yup, it's affecting everything ATM. Trying to get a fix out. Problem is they changed the SpikeGLX files on GIN to make them shorter, but made a header/file mismatch in the process.

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
Any idea on this error?
https://github.com/catalystneuro/nwb-conversion-tools/runs/7102719467?check_suite_focus=true

This is related to the newly cli-yaml test.

**Comment by CodyCBakerPhD** [comment]
> Any idea on this error?
https://github.com/catalystneuro/nwb-conversion-tools/runs/7102719467?check_suite_focus=true

> This is related to the newly cli-yaml test.

Not sure, I might have seen that before. But the fact that rerunning fixed it is strange indeed.

**Pull request merged**
