### PR TITLE
fix source_data_schema

### LINKED ISSUE #244: File and Directory annotations not showing up on schema
## Description

**Problem 1:**
PR #237 is supposed to auto infer File or Directory type of paths within source_data_schema from init, but it doesn't seem to be working.

**Problem 2**
This is the weirdest: after re-running the same Notebook cell, the following error track shows, apparently the type string is being changed somehow.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-6d29f0927059> in <module>
----> 1 OpenEphysRecordingExtractorInterface.get_source_schema()

/media/luiz/storage/Github/nwb-conversion-tools/nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py in get_source_schema(cls)
     18         """Compile input schema for the RecordingExtractor."""
     19         source_schema = get_schema_from_method_signature(
---> 20             class_method=cls.__init__, exclude=["recording_id", "experiment_id", "stub_test"]
     21         )
     22         source_schema["properties"]["folder_path"]["description"] = "Path to directory containing OpenEphys files."

/media/luiz/storage/Github/nwb-conversion-tools/nwb_conversion_tools/utils/json_schema.py in get_schema_from_method_signature(class_method, exclude)
    124                     else:
    125                         raise ValueError(
--> 126                             f"No valid arguments were found in the json type mapping {arg} for parameter {param}"
    127                         )
    128                     if arg == FilePathType:

ValueError: No valid arguments were found in the json type mapping ~FolderPathType for parameter folder_path: ~FolderPathType
```

## Steps to Reproduce
```
from nwb_conversion_tools import OpenEphysRecordingExtractorInterface
OpenEphysRecordingExtractorInterface.get_source_schema()
```

## Environment

    Python Executable: Conda or Python
    Python Version: Python 3.7.10
    Operating System: Linux
    PyNWB Version: master branch    

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

### PR DESCRIPTION
**Pull request by luiztauffer**
fix #244 

## Motivation

Issue #244 

## How to test the behavior?
```
from nwb_conversion_tools import OpenEphysRecordingExtractorInterface
OpenEphysRecordingExtractorInterface.get_source_schema()
```

### CODE REVIEW

**Comment by luiztauffer** [comment]
@CodyCBakerPhD all we needed was a proper dictionary update, using our awesome `dict_deep_update()`

The weird error with TypeVar an Jupyter autoreload still exists though

**Comment by CodyCBakerPhD** [comment]
@luiztauffer Check out my latest commit here, I was able to replicate your autoreload issue and simplified it to the following issue...

image

As you can see, with `TypeVar`, equality is checked at the object ID level, which changes when the values are reloaded from the module. Thus it is comparing two variables from two different environments, even though they have the same name. If `TypeVar` were an actual class, this wouldn't be an issue, but there wasn't a super good way to set up these `File` and `Folder PathType`s as strict subclasses.

Anyway, the fix is pretty simple. It switches the `annotation_type_map` to a dictionary literal of string keys for each class, and the annotation check is applied to the string name of the `Type`.

**Comment by CodyCBakerPhD** [comment]
Also, from the auto-populated checklist for the PR post that you deleted, the last item is including "fix #???" where ??? is the issue number as the first line of the PR so it automatically closes it upon merge - please remember to check that in the future. I've added it to your post now, though.

**Comment by luiztauffer** [comment]
@CodyCBakerPhD seems to have locally! Good to merge

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
